### PR TITLE
upgrade issue template to Github issue forms (Issue: #6)

### PR DESCRIPTION
**Pull request by prerna2712**
- Forked the repository
- Made the required changes
- Pushed to master
- Pull request created

### CODE REVIEW

**Comment by prerna2712** [comment]
Please review

**Comment by lohanidamodar** [comment]
@prerna2712  Great work. One more change before we can approve. We have made few changes in the language and also the format of Code of conduct. Please check https://github.com/appwrite/appwrite template and update accordingly.
Thank you.

**Comment by prerna2712** [comment]
Will get them corrected by today.

**Comment by prerna2712** [comment]
Updated the PR, please review

**Review by Meldiron — APPROVED** [review]
**Awesome** PR 🤯 Approved by me.

**Comment by prerna2712** [comment]
> **Awesome** PR 🤯 Approved by me.

Thank you so much 😁

**Review by stijnvdkolk — APPROVED** [review]
Looks good :D

**Review by stijnvdkolk — APPROVED** [review]

**Comment by Meldiron** [comment]
THANK YOU! All changes merged 🥳

Please reach out to `eldadfux` on our [Discord server](https://appwrite.io/discord) if you would like to claim your Appwrite swags! As a way of saying thank you, we would also love to invite you to join the Appwrite organization on GitHub. Please share your GitHub username with us on Discord.  

You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

Please feel free to look for more PRs you might be interested in helping with on our long list of [Hacktoberfest friendly issues](https://github.com/search?q=org%3Aappwrite+org%3Autopia-php+is%3Aissue+label%3Ahacktoberfest+created%3A%3E2021-01-01+is%3Aopen&type=issues) and help make Appwrite better :)

**Comment by prerna2712** [comment]
Thank you for merging my PR. The invitaion link seems broken.

**Pull request merged**
